version: '3.4'

services:
  db:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    container_name: postgres-playgound
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/postgresql/data
